- name: wait gitlab
  uri:
    url: "http://{{ groups.gitlabs[0] }}"
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  changed_when: false

- name: verify gitaly configuration
  command:
    cmd: gitlab-rake gitlab:gitaly:check

- name: verify gitaly-hooks configuration
  command:
    cmd: /opt/gitlab/embedded/bin/gitaly-hooks check /var/opt/gitlab/gitaly/config.toml
  delegate_to: '{{ item }}'
  with_items: '{{ groups.gitalies }}'
